import { useRef } from "react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Download, Printer } from "lucide-react";
import { useReactToPrint } from "react-to-print";
import jsPDF from "jspdf";

interface Finding {
  name: string;
  score: number;
}

interface ReportData {
  patientName: string;
  patientNumber: string;
  dateOfAnalysis: string;
  overallRisk: string;
  findings: Finding[];
  recommendation: string;
  xrayImageUrl: string;
}

interface ReportGeneratorProps {
  data: ReportData;
}

export const ReportGenerator = ({ data }: ReportGeneratorProps) => {
  const reportRef = useRef<HTMLDivElement>(null);

  const handlePrint = useReactToPrint({
    contentRef: reportRef,
    documentTitle: `X-Ray Report - ${data.patientNumber}`,
  });

  const handleDownloadPDF = () => {
    const pdf = new jsPDF({
      orientation: "portrait",
      unit: "mm",
      format: "a4",
    });

    // Add header
    pdf.setFontSize(20);
    pdf.text("Chest X-Ray Analysis Report", 105, 20, { align: "center" });

    // Add patient info
    pdf.setFontSize(12);
    pdf.text(`Patient: ${data.patientName}`, 20, 40);
    pdf.text(`Patient Number: ${data.patientNumber}`, 20, 48);
    pdf.text(`Date of Analysis: ${data.dateOfAnalysis}`, 20, 56);

    // Add overall risk
    pdf.setFontSize(14);
    pdf.text(`Overall Risk: ${data.overallRisk}`, 20, 70);

    // Add findings
    pdf.setFontSize(12);
    pdf.text("Findings:", 20, 85);
    
    let yPosition = 95;
    data.findings.forEach((finding, index) => {
      if (yPosition > 270) {
        pdf.addPage();
        yPosition = 20;
      }
      pdf.text(
        `${index + 1}. ${finding.name}: ${(finding.score * 100).toFixed(1)}%`,
        25,
        yPosition
      );
      yPosition += 8;
    });

    // Add recommendation
    if (yPosition > 240) {
      pdf.addPage();
      yPosition = 20;
    }
    pdf.setFontSize(12);
    pdf.text("Recommendation:", 20, yPosition + 10);
    
    const recommendationLines = pdf.splitTextToSize(data.recommendation, 170);
    pdf.text(recommendationLines, 20, yPosition + 20);

    // Add disclaimer
    const disclaimerY = yPosition + 20 + (recommendationLines.length * 7) + 10;
    if (disclaimerY > 260) {
      pdf.addPage();
      pdf.setFontSize(10);
      pdf.text("Disclaimer:", 20, 20);
      pdf.text(
        "This report is generated by AI and should be reviewed by a qualified medical professional.",
        20,
        28
      );
    } else {
      pdf.setFontSize(10);
      pdf.text("Disclaimer:", 20, disclaimerY);
      pdf.text(
        "This report is generated by AI and should be reviewed by a qualified medical professional.",
        20,
        disclaimerY + 8
      );
    }

    pdf.save(`xray-report-${data.patientNumber}-${Date.now()}.pdf`);
  };

  const getRiskColor = (risk: string) => {
    switch (risk?.toLowerCase()) {
      case "low":
        return "text-green-600 bg-green-50";
      case "moderate":
        return "text-yellow-600 bg-yellow-50";
      case "high":
        return "text-red-600 bg-red-50";
      default:
        return "text-gray-600 bg-gray-50";
    }
  };

  return (
    <Card className="p-6">
      <div className="flex justify-between items-center mb-6">
        <h2 className="text-2xl font-bold">Analysis Report</h2>
        <div className="flex gap-2">
          <Button variant="outline" onClick={() => handlePrint()}>
            <Printer className="h-4 w-4 mr-2" />
            Print
          </Button>
          <Button onClick={handleDownloadPDF}>
            <Download className="h-4 w-4 mr-2" />
            Download PDF
          </Button>
        </div>
      </div>

      <div ref={reportRef} className="space-y-6 print:p-8">
        {/* Header */}
        <div className="text-center border-b pb-4">
          <h1 className="text-3xl font-bold mb-2">Chest X-Ray Analysis Report</h1>
          <p className="text-muted-foreground">AI-Powered Diagnostic Assistance</p>
        </div>

        {/* Patient Information */}
        <div className="grid grid-cols-2 gap-4">
          <div>
            <p className="text-sm text-muted-foreground">Patient Name</p>
            <p className="font-semibold">{data.patientName}</p>
          </div>
          <div>
            <p className="text-sm text-muted-foreground">Patient Number</p>
            <p className="font-semibold">{data.patientNumber}</p>
          </div>
          <div>
            <p className="text-sm text-muted-foreground">Date of Analysis</p>
            <p className="font-semibold">{data.dateOfAnalysis}</p>
          </div>
          <div>
            <p className="text-sm text-muted-foreground">Overall Risk</p>
            <p className={`font-semibold inline-block px-3 py-1 rounded ${getRiskColor(data.overallRisk)}`}>
              {data.overallRisk}
            </p>
          </div>
        </div>

        {/* X-Ray Image */}
        <div className="border rounded-lg p-4 bg-black">
          <img
            src={data.xrayImageUrl}
            alt="Chest X-Ray"
            className="max-w-full h-auto mx-auto"
            style={{ maxHeight: "400px" }}
          />
        </div>

        {/* Findings */}
        <div>
          <h3 className="text-xl font-bold mb-4">Detailed Findings</h3>
          <div className="space-y-2">
            {data.findings
              .sort((a, b) => b.score - a.score)
              .map((finding, index) => (
                <div
                  key={index}
                  className="flex justify-between items-center p-3 rounded bg-muted"
                >
                  <span className="font-medium">{finding.name}</span>
                  <span className="text-muted-foreground">
                    {(finding.score * 100).toFixed(1)}%
                  </span>
                </div>
              ))}
          </div>
        </div>

        {/* Recommendation */}
        <div>
          <h3 className="text-xl font-bold mb-2">Recommendation</h3>
          <p className="text-muted-foreground leading-relaxed">{data.recommendation}</p>
        </div>

        {/* Disclaimer */}
        <div className="border-t pt-4 text-sm text-muted-foreground">
          <p className="font-semibold mb-1">Disclaimer:</p>
          <p>
            This report is generated by an AI system and should be reviewed by a qualified
            medical professional before making any clinical decisions. The AI analysis is
            intended to assist healthcare providers and should not replace professional
            medical judgment.
          </p>
        </div>
      </div>
    </Card>
  );
};